services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - notebook:/home/jupyter
    ports:
      # "inner:outer" - inner always needs to be 8888,
      # outer can be whatever port you have vacant on your system
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=easy

volumes:
  notebook:
    driver: local
    driver_opts:
      type: none
      device: ./notebook
      o: bind
